/* ------------------------------------------------------------------ *
 *  StyleGrammar catalogue — the architectural rules per style.
 *
 *  Each style declares *real* architectural characteristics: which
 *  plan footprints and volumetric strategies it allows, its roof
 *  language, how it glazes each room type, its entrance, balconies,
 *  facade vocabulary (fins / jaali / cladding / feature pier / string
 *  course / chajja / verandah / pergola / tower) and materials.
 *
 *  The grammar is pure data + no geometry. `generateDesign()` resolves
 *  it against a floor plan + a seed into a concrete DesignSpec, which
 *  the Blender generator turns into a GLB.
 *
 *  Calibrated against real South-Asian villas — see each style's
 *  `refs`. The UI `character` maps 1:1 to a StyleId.
 * ------------------------------------------------------------------ */

import type { Character } from '../lib/model/brief.ts'
import type { RoomClass, RoomWindowRule, StyleGrammar, StyleId } from './types.ts'

/* ---- UI character  <->  grammar style ---------------------------- */

export const STYLE_OF_CHARACTER: Record<Character, StyleId> = {
  'modern-indian': 'modern_indian',
  'contemporary-indian': 'contemporary_indian',
  'modern-kerala': 'modern_kerala',
  'kerala-contemporary': 'kerala_contemporary',
  'luxury-indian': 'luxury_indian_villa',
  'tropical-indian': 'tropical_indian_modern',
  'minimal-indian': 'minimal_indian',
  'courtyard-indian': 'courtyard_indian_modern',
}

export const CHARACTER_OF_STYLE: Record<StyleId, Character> = Object.fromEntries(
  Object.entries(STYLE_OF_CHARACTER).map(([c, s]) => [s, c]),
) as Record<StyleId, Character>

/* ---- reusable per-room window rules ----------------------------- */

const W = (r: RoomWindowRule): RoomWindowRule => r

const ROOM_W = {
  livingLarge: W({
    preferred: 2,
    max: 3,
    widthMm: [1800, 3600],
    heightMm: [1800, 2600],
    sillMm: 450,
    privacy: false,
    allowStrip: true,
    allowPicture: true,
  }),
  livingModerate: W({
    preferred: 2,
    max: 2,
    widthMm: [1500, 2600],
    heightMm: [1500, 2200],
    sillMm: 600,
    privacy: false,
    allowStrip: true,
    allowPicture: false,
  }),
  diningMod: W({
    preferred: 1,
    max: 2,
    widthMm: [1400, 2400],
    heightMm: [1400, 2100],
    sillMm: 700,
    privacy: false,
    allowStrip: true,
    allowPicture: false,
  }),
  kitchen: W({
    preferred: 1,
    max: 1,
    widthMm: [1000, 1600],
    heightMm: [1000, 1400],
    sillMm: 1050,
    privacy: false,
    allowStrip: false,
    allowPicture: false,
  }),
  bedroom: W({
    preferred: 1,
    max: 2,
    widthMm: [1200, 2100],
    heightMm: [1350, 1800],
    sillMm: 750,
    privacy: false,
    allowStrip: false,
    allowPicture: false,
  }),
  bedroomGenerous: W({
    preferred: 2,
    max: 2,
    widthMm: [1400, 2400],
    heightMm: [1500, 2100],
    sillMm: 600,
    privacy: false,
    allowStrip: false,
    allowPicture: true,
  }),
  master: W({
    preferred: 2,
    max: 2,
    widthMm: [1500, 2600],
    heightMm: [1500, 2200],
    sillMm: 600,
    privacy: false,
    allowStrip: false,
    allowPicture: true,
  }),
  bath: W({
    preferred: 1,
    max: 1,
    widthMm: [500, 800],
    heightMm: [500, 900],
    sillMm: 1500,
    privacy: true,
    allowStrip: false,
    allowPicture: false,
  }),
  study: W({
    preferred: 1,
    max: 2,
    widthMm: [1200, 2000],
    heightMm: [1300, 1900],
    sillMm: 750,
    privacy: false,
    allowStrip: false,
    allowPicture: false,
  }),
  stair: W({
    preferred: 0,
    max: 1,
    widthMm: [700, 1400],
    heightMm: [1800, 3000],
    sillMm: 900,
    privacy: false,
    allowStrip: false,
    allowPicture: false,
  }),
  utility: W({
    preferred: 1,
    max: 1,
    widthMm: [600, 1000],
    heightMm: [700, 1100],
    sillMm: 1200,
    privacy: true,
    allowStrip: false,
    allowPicture: false,
  }),
  poojaSlot: W({
    preferred: 0,
    max: 1,
    widthMm: [400, 700],
    heightMm: [900, 1500],
    sillMm: 900,
    privacy: false,
    allowStrip: false,
    allowPicture: false,
  }),
} as const

const COMMON_BY_ROOM: Partial<Record<RoomClass, RoomWindowRule>> = {
  kitchen: ROOM_W.kitchen,
  bathroom: ROOM_W.bath,
  utility: ROOM_W.utility,
  study: ROOM_W.study,
  stair: ROOM_W.stair,
  pooja: ROOM_W.poojaSlot,
}

/* ================================================================== *
 *  THE 8 STYLES
 * ================================================================== */

export const STYLE_GRAMMARS: Record<StyleId, StyleGrammar> = {
  /* -------------------------------------------------------------- */
  modern_indian: {
    id: 'modern_indian',
    label: 'Modern Indian',
    summary:
      'Stacked and offset white plaster volumes, thin floating slabs, a cantilevered upper floor, vertical shading fins, a jaali-clad stair tower, stone feature walls and controlled glazing.',
    refs: ['Ahmedabad / Hyderabad contemporary villas — offset white boxes, deep cantilevers, vertical fins, riven-stone piers'],
    massing: {
      planShapes: ['rectangular', 'l_shape', 'square', 't_shape'],
      strategies: [
        { kind: 'offset_volumes', weight: 4 },
        { kind: 'cantilever', weight: 3 },
        { kind: 'stacked', weight: 2 },
        { kind: 'split_mass', weight: 2 },
        { kind: 'stepped', weight: 1 },
      ],
      storeyOffsetMm: [900, 2200],
      cantileverMm: [800, 1500],
      splitGapMm: [1800, 3000],
      groundExtendMm: 2200,
      featureTowerChance: 0.55,
      maxAspect: 1.9,
    },
    roof: {
      kind: 'flat_band',
      pitchDeg: [0, 0],
      eaveMm: [600, 820],
      parapetMm: 0,
      bandMm: 210,
      perBlock: true,
      terraceChance: 0.6,
    },
    window: {
      byRoom: { ...COMMON_BY_ROOM, living: ROOM_W.livingLarge, dining: ROOM_W.diningMod, bedroom: ROOM_W.bedroom, master: ROOM_W.master },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.38,
      minWallBetweenWindowsMm: 700,
      minCornerOffsetMm: 500,
      minDoorWindowDistanceMm: 450,
      stripGlazingChance: 0.4,
      pictureWindowChance: 0.3,
      upperPrivacyBias: 0.35,
    },
    door: { entryWidthMm: [1500, 1800], internalWidthMm: 900, doubleLeafEntry: true, entryCanopyMm: 900, doubleHeightEntry: false, porteCochere: false },
    balcony: { rooms: ['master', 'bedroom', 'living'], depthMm: [1400, 1900], minWidthMm: 1800, maxPerFloor: 2, recessedChance: 0.5, railStyle: 'glass', wrapVerandah: false },
    facade: {
      verticalFinsChance: 0.7,
      finDepthMm: [250, 380],
      jaaliScreenChance: 0.5,
      jaaliWhere: ['entry', 'stair'],
      cladPanels: { material: 'teak', widthMm: [1400, 1900], twoStorey: false },
      featurePier: { material: 'stone_dark', chance: 0.6 },
      stringCourseMm: 60,
      chajjaMm: 0,
      plinthMm: 150,
      baseCladding: 'stone_dark',
      pergola: ['roof'],
      verandah: null,
    },
    material: {
      palette: 'white',
      wall: '#ece7db',
      base: '#33322f',
      trim: '#f6f4ee',
      roof: '#f6f4ee',
      frame: '#24242a',
      accent: '#96683c',
      glassTint: '#2f3e48',
      variants: { wall: ['#efe9dd', '#e8e2d4'], accent: ['#8a5c34', '#7a5230'] },
      seededSwaps: 2,
    },
    constraints: { window: { maxWindowRatio: 0.38, minWallBetweenWindowsMm: 700, minCornerOffsetMm: 500, minDoorWindowDistanceMm: 450, maxWindowsPerRoom: 3, preferredWindowsPerRoom: 1 } },
  },

  /* -------------------------------------------------------------- */
  contemporary_indian: {
    id: 'contemporary_indian',
    label: 'Contemporary Indian',
    summary:
      'Off-white plaster planes over a dark stone-clad ground floor, wide aluminium sliders under deep flat hoods, a floating roof, a timber screen to the stair and a recessed double-height entrance.',
    refs: ['Pune / Bengaluru farmhouse villas — plaster over basalt base, deep chajja hoods, double-height glazed entry'],
    massing: {
      planShapes: ['rectangular', 'l_shape', 'square', 't_shape'],
      strategies: [
        { kind: 'stacked', weight: 4 },
        { kind: 'cantilever', weight: 3 },
        { kind: 'offset_volumes', weight: 2 },
        { kind: 'split_mass', weight: 1 },
      ],
      storeyOffsetMm: [600, 1400],
      cantileverMm: [900, 1600],
      splitGapMm: [2000, 3200],
      groundExtendMm: 2400,
      featureTowerChance: 0.2,
      maxAspect: 2.0,
    },
    roof: { kind: 'flat_eave', pitchDeg: [0, 0], eaveMm: [500, 700], parapetMm: 90, bandMm: 0, perBlock: false, terraceChance: 0.5 },
    window: {
      byRoom: { ...COMMON_BY_ROOM, living: ROOM_W.livingLarge, dining: ROOM_W.diningMod, bedroom: ROOM_W.bedroomGenerous, master: ROOM_W.master },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.46,
      minWallBetweenWindowsMm: 650,
      minCornerOffsetMm: 450,
      minDoorWindowDistanceMm: 400,
      stripGlazingChance: 0.55,
      pictureWindowChance: 0.4,
      upperPrivacyBias: 0.3,
    },
    door: { entryWidthMm: [1500, 1900], internalWidthMm: 900, doubleLeafEntry: true, entryCanopyMm: 0, doubleHeightEntry: true, porteCochere: false },
    balcony: { rooms: ['master', 'bedroom'], depthMm: [1200, 1600], minWidthMm: 1600, maxPerFloor: 2, recessedChance: 0.6, railStyle: 'bar', wrapVerandah: false },
    facade: {
      verticalFinsChance: 0.35,
      finDepthMm: [200, 300],
      jaaliScreenChance: 0.55,
      jaaliWhere: ['stair'],
      cladPanels: { material: 'teak', widthMm: [1500, 2000], twoStorey: true },
      featurePier: { material: 'stone_dark', chance: 0.5 },
      stringCourseMm: 40,
      chajjaMm: 520,
      plinthMm: 200,
      baseCladding: 'stone_dark',
      pergola: [],
      verandah: null,
    },
    material: {
      palette: 'grey_concrete',
      wall: '#efe9dd',
      base: '#33322f',
      trim: '#f6f4ee',
      roof: '#f4f2ec',
      frame: '#24242a',
      accent: '#96683c',
      glassTint: '#33424c',
      variants: { wall: ['#ece6d8', '#e5ddcb'], base: ['#3a3936', '#2c2b28'] },
      seededSwaps: 2,
    },
  },

  /* -------------------------------------------------------------- */
  modern_kerala: {
    id: 'modern_kerala',
    label: 'Modern Kerala',
    summary:
      'Low-pitched clay-tile hip roofs with wide overhanging eaves, white plaster over a laterite base, a deep shaded verandah on square columns, teak-framed shuttered windows and a brick jaali.',
    refs: ['Thrissur / Kottayam nalukettu-derived homes — tiled hips, wide eaves, laterite plinth, columned verandah'],
    massing: {
      planShapes: ['rectangular', 'l_shape', 'u_shape', 'courtyard'],
      strategies: [
        { kind: 'stacked', weight: 4 },
        { kind: 'linear', weight: 2 },
        { kind: 'split_mass', weight: 2 },
        { kind: 'stepped', weight: 1 },
      ],
      storeyOffsetMm: [300, 800],
      cantileverMm: [0, 0],
      splitGapMm: [1800, 2600],
      groundExtendMm: 1500,
      featureTowerChance: 0.05,
      maxAspect: 2.2,
    },
    roof: { kind: 'hip', pitchDeg: [22, 28], eaveMm: [800, 1000], parapetMm: 0, bandMm: 0, perBlock: true, terraceChance: 0.05 },
    window: {
      byRoom: { ...COMMON_BY_ROOM, living: ROOM_W.livingModerate, dining: ROOM_W.diningMod, bedroom: ROOM_W.bedroom, master: ROOM_W.bedroomGenerous },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.34,
      minWallBetweenWindowsMm: 750,
      minCornerOffsetMm: 500,
      minDoorWindowDistanceMm: 450,
      stripGlazingChance: 0.15,
      pictureWindowChance: 0.15,
      upperPrivacyBias: 0.2,
    },
    door: { entryWidthMm: [1400, 1700], internalWidthMm: 900, doubleLeafEntry: true, entryCanopyMm: 0, doubleHeightEntry: false, porteCochere: false },
    balcony: { rooms: ['master'], depthMm: [1400, 1900], minWidthMm: 1800, maxPerFloor: 1, recessedChance: 0.3, railStyle: 'bar', wrapVerandah: true },
    facade: {
      verticalFinsChance: 0.1,
      finDepthMm: [150, 220],
      jaaliScreenChance: 0.6,
      jaaliWhere: ['stair', 'street_wall'],
      cladPanels: { material: 'teak', widthMm: [1600, 2000], twoStorey: false },
      featurePier: { material: 'laterite', chance: 0.4 },
      stringCourseMm: 90,
      chajjaMm: 560,
      plinthMm: 260,
      baseCladding: 'laterite',
      pergola: ['verandah'],
      verandah: { depthMm: [1900, 2400], columns: 'square', columnMm: 320, wrapCourt: false },
    },
    material: {
      palette: 'earth',
      wall: '#ece7db',
      base: '#8a7355',
      trim: '#f6f4ee',
      roof: '#9c5a44',
      frame: '#96683c',
      accent: '#96683c',
      glassTint: '#33424c',
      variants: { roof: ['#a85f47', '#8f5540'], base: ['#8f7a5c', '#7f6a4c'] },
      seededSwaps: 1,
    },
  },

  /* -------------------------------------------------------------- */
  kerala_contemporary: {
    id: 'kerala_contemporary',
    label: 'Kerala Contemporary',
    summary:
      'Stepped flat roofs in thick white fascia bands, cream plaster with floor-line string courses and chajja hoods, two-storey teak-batten panels framed in white, a dark stone entry pier and a timber jaali.',
    refs: ['Kozhikode / Kochi contemporary homes — stepped white roof bands, framed teak panels, stone entry pier'],
    massing: {
      planShapes: ['rectangular', 'l_shape', 'square', 't_shape'],
      strategies: [
        { kind: 'stepped', weight: 4 },
        { kind: 'stacked', weight: 2 },
        { kind: 'offset_volumes', weight: 2 },
        { kind: 'cantilever', weight: 1 },
      ],
      storeyOffsetMm: [800, 1600],
      cantileverMm: [400, 900],
      splitGapMm: [1800, 2800],
      groundExtendMm: 1800,
      featureTowerChance: 0.15,
      maxAspect: 2.0,
    },
    roof: { kind: 'flat_band', pitchDeg: [0, 0], eaveMm: [200, 320], parapetMm: 0, bandMm: 420, perBlock: true, terraceChance: 0.5 },
    window: {
      byRoom: { ...COMMON_BY_ROOM, living: ROOM_W.livingLarge, dining: ROOM_W.diningMod, bedroom: ROOM_W.bedroom, master: ROOM_W.master },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.42,
      minWallBetweenWindowsMm: 650,
      minCornerOffsetMm: 450,
      minDoorWindowDistanceMm: 420,
      stripGlazingChance: 0.4,
      pictureWindowChance: 0.35,
      upperPrivacyBias: 0.3,
    },
    door: { entryWidthMm: [1500, 1800], internalWidthMm: 900, doubleLeafEntry: true, entryCanopyMm: 0, doubleHeightEntry: false, porteCochere: false },
    balcony: { rooms: ['master', 'bedroom'], depthMm: [1400, 1700], minWidthMm: 1700, maxPerFloor: 2, recessedChance: 0.4, railStyle: 'bar', wrapVerandah: false },
    facade: {
      verticalFinsChance: 0.25,
      finDepthMm: [200, 300],
      jaaliScreenChance: 0.65,
      jaaliWhere: ['entry', 'stair'],
      cladPanels: { material: 'teak', widthMm: [1700, 2100], twoStorey: true },
      featurePier: { material: 'stone_dark', chance: 0.7 },
      stringCourseMm: 110,
      chajjaMm: 520,
      plinthMm: 200,
      baseCladding: 'stone_dark',
      pergola: [],
      verandah: null,
    },
    material: {
      palette: 'white',
      wall: '#efe9dd',
      base: '#33322f',
      trim: '#f8f6f1',
      roof: '#f8f6f1',
      frame: '#96683c',
      accent: '#96683c',
      glassTint: '#33424c',
      variants: { wall: ['#ece6d8', '#f1ebdf'] },
      seededSwaps: 1,
    },
  },

  /* -------------------------------------------------------------- */
  luxury_indian_villa: {
    id: 'luxury_indian_villa',
    label: 'Luxury Indian villa',
    summary:
      'A dramatic double-height entrance under a large canopy on tapered stone columns, travertine planes over a granite plinth, deep floating overhangs, full-height bronze-framed glazing, large balconies and a porte-cochere.',
    refs: ['Delhi NCR / Udaipur luxury villas — double-height portico, travertine over granite, wrap verandah, reflecting pool'],
    massing: {
      planShapes: ['rectangular', 'l_shape', 'u_shape', 'courtyard', 't_shape'],
      strategies: [
        { kind: 'split_mass', weight: 4 },
        { kind: 'cantilever', weight: 3 },
        { kind: 'offset_volumes', weight: 3 },
        { kind: 'stacked', weight: 2 },
        { kind: 'stepped', weight: 1 },
      ],
      storeyOffsetMm: [1200, 2400],
      cantileverMm: [1200, 1800],
      splitGapMm: [2400, 3600],
      groundExtendMm: 3000,
      featureTowerChance: 0.3,
      maxAspect: 2.4,
    },
    roof: { kind: 'flat_eave', pitchDeg: [0, 0], eaveMm: [900, 1200], parapetMm: 80, bandMm: 0, perBlock: false, terraceChance: 0.4 },
    window: {
      byRoom: {
        ...COMMON_BY_ROOM,
        living: W({ preferred: 3, max: 3, widthMm: [2000, 4200], heightMm: [2200, 3200], sillMm: 250, privacy: false, allowStrip: true, allowPicture: true }),
        dining: ROOM_W.livingModerate,
        bedroom: W({ preferred: 2, max: 3, widthMm: [1600, 2800], heightMm: [1800, 2600], sillMm: 400, privacy: false, allowStrip: false, allowPicture: true }),
        master: W({ preferred: 2, max: 3, widthMm: [1800, 3200], heightMm: [1900, 2800], sillMm: 350, privacy: false, allowStrip: true, allowPicture: true }),
        study: W({ preferred: 2, max: 2, widthMm: [1400, 2400], heightMm: [1500, 2200], sillMm: 500, privacy: false, allowStrip: false, allowPicture: true }),
      },
      fallback: ROOM_W.bedroomGenerous,
      maxWindowRatio: 0.52,
      minWallBetweenWindowsMm: 800,
      minCornerOffsetMm: 550,
      minDoorWindowDistanceMm: 500,
      stripGlazingChance: 0.6,
      pictureWindowChance: 0.55,
      upperPrivacyBias: 0.2,
    },
    door: { entryWidthMm: [1800, 2400], internalWidthMm: 1000, doubleLeafEntry: true, entryCanopyMm: 2000, doubleHeightEntry: true, porteCochere: true },
    balcony: { rooms: ['master', 'bedroom', 'living', 'study'], depthMm: [1800, 2600], minWidthMm: 2000, maxPerFloor: 3, recessedChance: 0.35, railStyle: 'glass', wrapVerandah: true },
    facade: {
      verticalFinsChance: 0.3,
      finDepthMm: [250, 400],
      jaaliScreenChance: 0.35,
      jaaliWhere: ['court'],
      cladPanels: { material: 'travertine', widthMm: [1800, 2400], twoStorey: true },
      featurePier: { material: 'stone_dark', chance: 0.6 },
      stringCourseMm: 120,
      chajjaMm: 640,
      plinthMm: 320,
      baseCladding: 'stone_dark',
      pergola: ['roof', 'verandah'],
      verandah: { depthMm: [2200, 2800], columns: 'tapered', columnMm: 460, wrapCourt: true },
    },
    material: {
      palette: 'warm_stone',
      wall: '#e9e3d4',
      base: '#3b3a37',
      trim: '#f2efe6',
      roof: '#f6f4ee',
      frame: '#5a4a32',
      accent: '#8a7355',
      glassTint: '#2b3841',
      variants: { wall: ['#ece6d7', '#e4ddcc'], base: ['#3f3e3a', '#333230'], accent: ['#8f7a5c', '#7f6a4c'] },
      seededSwaps: 2,
    },
    constraints: { maxCoverage: 0.6, floorHeightMm: [3300, 4600], massing: { maxCantileverMm: 2000, minLinkMm: 2200, maxStoreyOffsetMm: 2800 } },
  },

  /* -------------------------------------------------------------- */
  tropical_indian_modern: {
    id: 'tropical_indian_modern',
    label: 'Tropical Indian modern',
    summary:
      'Broad low mono-pitch roofs with very deep overhangs on exposed rafters, white and warm-timber planes, a deep wrap verandah on slim round columns, floor-to-ceiling louvred glazing, a big terracotta jaali and a pergola.',
    refs: ['Goa / coastal Karnataka houses — deep mono-slope overhangs, wrap verandah, terracotta jaali, pergola sit-out'],
    massing: {
      planShapes: ['rectangular', 'l_shape', 'courtyard'],
      strategies: [
        { kind: 'linear', weight: 4 },
        { kind: 'split_mass', weight: 3 },
        { kind: 'stacked', weight: 2 },
        { kind: 'stepped', weight: 1 },
      ],
      storeyOffsetMm: [400, 1000],
      cantileverMm: [0, 800],
      splitGapMm: [1800, 3000],
      groundExtendMm: 1200,
      featureTowerChance: 0.05,
      maxAspect: 2.6,
    },
    roof: { kind: 'mono_slope', pitchDeg: [12, 20], eaveMm: [1000, 1400], parapetMm: 0, bandMm: 0, perBlock: true, terraceChance: 0.1 },
    window: {
      byRoom: {
        ...COMMON_BY_ROOM,
        living: W({ preferred: 3, max: 3, widthMm: [2000, 3800], heightMm: [2000, 2800], sillMm: 200, privacy: false, allowStrip: true, allowPicture: true }),
        dining: ROOM_W.livingModerate,
        bedroom: W({ preferred: 1, max: 2, widthMm: [1400, 2400], heightMm: [1600, 2400], sillMm: 300, privacy: false, allowStrip: false, allowPicture: false }),
        master: W({ preferred: 2, max: 2, widthMm: [1600, 2800], heightMm: [1800, 2600], sillMm: 250, privacy: false, allowStrip: true, allowPicture: true }),
      },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.5,
      minWallBetweenWindowsMm: 600,
      minCornerOffsetMm: 450,
      minDoorWindowDistanceMm: 400,
      stripGlazingChance: 0.55,
      pictureWindowChance: 0.4,
      upperPrivacyBias: 0.25,
    },
    door: { entryWidthMm: [1500, 1900], internalWidthMm: 900, doubleLeafEntry: true, entryCanopyMm: 0, doubleHeightEntry: false, porteCochere: false },
    balcony: { rooms: ['master'], depthMm: [1600, 2200], minWidthMm: 1800, maxPerFloor: 1, recessedChance: 0.3, railStyle: 'bar', wrapVerandah: true },
    facade: {
      verticalFinsChance: 0.55,
      finDepthMm: [250, 380],
      jaaliScreenChance: 0.7,
      jaaliWhere: ['street_wall'],
      cladPanels: { material: 'teak', widthMm: [1800, 2200], twoStorey: false },
      featurePier: { material: 'brick', chance: 0.3 },
      stringCourseMm: 0,
      chajjaMm: 300,
      plinthMm: 200,
      baseCladding: null,
      pergola: ['verandah', 'roof'],
      verandah: { depthMm: [2200, 2600], columns: 'round', columnMm: 260, wrapCourt: true },
    },
    material: {
      palette: 'white',
      wall: '#ece7db',
      base: '#c6bfae',
      trim: '#f6f4ee',
      roof: '#e9e6df',
      frame: '#96683c',
      accent: '#a24b34',
      glassTint: '#33424c',
      variants: { wall: ['#efe9dd', '#e7e0d1'], accent: ['#a85238', '#96432f'] },
      seededSwaps: 2,
    },
  },

  /* -------------------------------------------------------------- */
  minimal_indian: {
    id: 'minimal_indian',
    label: 'Minimal Indian',
    summary:
      'Quiet sand-plaster planes, one thin oversailing flat roof with a crisp shadow line, a few large timber-framed openings under deep hoods, a broad teak-batten screen and very restrained detailing.',
    refs: ['Ahmedabad / Auroville minimal houses — one thin roof, few large openings, teak screen, gravel + a single tree'],
    massing: {
      planShapes: ['rectangular', 'square', 'l_shape'],
      strategies: [
        { kind: 'stacked', weight: 6 },
        { kind: 'linear', weight: 2 },
        { kind: 'stepped', weight: 1 },
      ],
      storeyOffsetMm: [0, 600],
      cantileverMm: [0, 600],
      splitGapMm: [1800, 2400],
      groundExtendMm: 800,
      featureTowerChance: 0,
      maxAspect: 1.9,
    },
    roof: { kind: 'flat_eave', pitchDeg: [0, 0], eaveMm: [450, 620], parapetMm: 120, bandMm: 0, perBlock: false, terraceChance: 0.3 },
    window: {
      byRoom: {
        ...COMMON_BY_ROOM,
        living: W({ preferred: 1, max: 2, widthMm: [2000, 3400], heightMm: [1900, 2600], sillMm: 500, privacy: false, allowStrip: false, allowPicture: true }),
        dining: W({ preferred: 1, max: 1, widthMm: [1600, 2600], heightMm: [1500, 2100], sillMm: 700, privacy: false, allowStrip: false, allowPicture: true }),
        bedroom: W({ preferred: 1, max: 1, widthMm: [1400, 2200], heightMm: [1500, 1900], sillMm: 700, privacy: false, allowStrip: false, allowPicture: false }),
        master: W({ preferred: 1, max: 2, widthMm: [1600, 2600], heightMm: [1600, 2100], sillMm: 600, privacy: false, allowStrip: false, allowPicture: true }),
      },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.36,
      minWallBetweenWindowsMm: 900,
      minCornerOffsetMm: 600,
      minDoorWindowDistanceMm: 500,
      stripGlazingChance: 0.2,
      pictureWindowChance: 0.55,
      upperPrivacyBias: 0.4,
    },
    door: { entryWidthMm: [1400, 1700], internalWidthMm: 900, doubleLeafEntry: false, entryCanopyMm: 0, doubleHeightEntry: false, porteCochere: false },
    balcony: { rooms: ['master'], depthMm: [1200, 1500], minWidthMm: 1600, maxPerFloor: 1, recessedChance: 0.7, railStyle: 'baluster', wrapVerandah: false },
    facade: {
      verticalFinsChance: 0.1,
      finDepthMm: [180, 260],
      jaaliScreenChance: 0.15,
      jaaliWhere: ['stair'],
      cladPanels: { material: 'teak', widthMm: [1800, 2200], twoStorey: false },
      featurePier: { material: 'stone_dark', chance: 0.25 },
      stringCourseMm: 0,
      chajjaMm: 600,
      plinthMm: 110,
      baseCladding: null,
      pergola: [],
      verandah: null,
    },
    material: {
      palette: 'earth',
      wall: '#e6e0d3',
      base: '#c6bfae',
      trim: '#f2efe6',
      roof: '#f6f4ee',
      frame: '#96683c',
      accent: '#54504a',
      glassTint: '#33424c',
      variants: { wall: ['#e9e3d6', '#e2dccf'] },
      seededSwaps: 1,
    },
  },

  /* -------------------------------------------------------------- */
  courtyard_indian_modern: {
    id: 'courtyard_indian_modern',
    label: 'Courtyard Indian modern',
    summary:
      'Single- and double-height wings wrapping an open planted courtyard, a shaded verandah on square columns running around the court, large terracotta jaali screens to the street, and flat roofs with thin fascias and deep chajja.',
    refs: ['Ahmedabad / Bengaluru courtyard houses — wings around a planted court, verandah gallery, street jaali screen'],
    massing: {
      planShapes: ['courtyard', 'u_shape', 'l_shape', 't_shape'],
      strategies: [
        { kind: 'stacked', weight: 4 },
        { kind: 'split_mass', weight: 3 },
        { kind: 'linear', weight: 2 },
        { kind: 'stepped', weight: 1 },
      ],
      storeyOffsetMm: [400, 1000],
      cantileverMm: [0, 600],
      splitGapMm: [1800, 2800],
      groundExtendMm: 1000,
      featureTowerChance: 0.05,
      maxAspect: 1.7,
    },
    roof: { kind: 'flat_eave', pitchDeg: [0, 0], eaveMm: [500, 650], parapetMm: 110, bandMm: 0, perBlock: true, terraceChance: 0.3 },
    window: {
      byRoom: {
        ...COMMON_BY_ROOM,
        living: W({ preferred: 3, max: 3, widthMm: [1800, 3600], heightMm: [2000, 2800], sillMm: 350, privacy: false, allowStrip: true, allowPicture: true }),
        dining: ROOM_W.diningMod,
        bedroom: W({ preferred: 1, max: 2, widthMm: [1300, 2200], heightMm: [1500, 2100], sillMm: 650, privacy: false, allowStrip: false, allowPicture: false }),
        master: ROOM_W.master,
      },
      fallback: ROOM_W.bedroom,
      maxWindowRatio: 0.44,
      minWallBetweenWindowsMm: 650,
      minCornerOffsetMm: 450,
      minDoorWindowDistanceMm: 420,
      stripGlazingChance: 0.6,
      pictureWindowChance: 0.35,
      upperPrivacyBias: 0.5,
    },
    door: { entryWidthMm: [1500, 1800], internalWidthMm: 900, doubleLeafEntry: true, entryCanopyMm: 0, doubleHeightEntry: false, porteCochere: false },
    balcony: { rooms: ['master', 'bedroom'], depthMm: [1400, 1800], minWidthMm: 1700, maxPerFloor: 2, recessedChance: 0.4, railStyle: 'bar', wrapVerandah: true },
    facade: {
      verticalFinsChance: 0.2,
      finDepthMm: [200, 300],
      jaaliScreenChance: 0.75,
      jaaliWhere: ['street_wall', 'court'],
      cladPanels: { material: 'teak', widthMm: [1600, 2000], twoStorey: false },
      featurePier: { material: 'brick', chance: 0.4 },
      stringCourseMm: 80,
      chajjaMm: 540,
      plinthMm: 170,
      baseCladding: null,
      pergola: ['verandah'],
      verandah: { depthMm: [1900, 2200], columns: 'square', columnMm: 300, wrapCourt: true },
    },
    material: {
      palette: 'white',
      wall: '#ece7db',
      base: '#c6bfae',
      trim: '#f6f4ee',
      roof: '#f4f2ec',
      frame: '#96683c',
      accent: '#a24b34',
      glassTint: '#33424c',
      variants: { wall: ['#efe9dd', '#e8e1d2'], accent: ['#a85238', '#9c4733'] },
      seededSwaps: 2,
    },
  },
}

/* ---- accessors ------------------------------------------------- */

export function styleGrammar(id: StyleId): StyleGrammar {
  return STYLE_GRAMMARS[id]
}

export function grammarForCharacter(character: Character): StyleGrammar {
  return STYLE_GRAMMARS[STYLE_OF_CHARACTER[character]]
}
