import { useState } from 'react'
import { Link } from 'react-router-dom'
import type { CostEstimate } from '@/lib/cost/index.ts'
import { boqCsv } from '@/lib/cost/index.ts'
import { formatINR, formatRange } from '@/lib/format.ts'
import { Field } from '@/components/ui/controls.tsx'
import { policy, type CostSelection } from '@/lib/cost/specifications.ts'
import { cx } from '@/lib/cx.ts'

const quantityGroups = [
  ['Earthwork & foundation', ['earthwork.', 'concrete.footings', 'concrete.plinthBeams']],
  ['Structure', ['concrete.columns', 'concrete.beams', 'concrete.slabs', 'concrete.stairs', 'concrete.lintels', 'concrete.chajjas']],
  ['Masonry & plaster', ['masonry.', 'plaster.']],
  ['Finishes', ['flooring', 'skirting', 'wallTiles.', 'waterproofing.', 'paint.', 'parapet', 'external.']],
  ['Openings', ['doors.', 'windows.', 'glazing', 'grills', 'railings.']],
  ['Services', ['plumbing.', 'electrical.']],
] as const
export function QuantitiesView({ cost }: { cost: CostEstimate }) {
  const [floor, setFloor] = useState('all'), q = cost.quantities
  const current = floor === 'all' ? q.total : q.perFloor.find(f => String(f.level) === floor) ?? q.total
  return <section><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-display text-2xl">Measured quantities</h2><p className="mt-2 text-xs text-ink-dim">Read-only measurements from your plan. Net areas exclude openings and voids where applicable.</p></div><label className="text-xs">Floor<select aria-label="Quantity floor filter" className="mt-2 block border border-line bg-bg px-3 py-2" value={floor} onChange={e => setFloor(e.target.value)}><option value="all">All floors</option>{q.perFloor.map(f => <option key={f.level} value={f.level}>{f.name}</option>)}</select></label></div>
    <div className="mt-6 grid gap-x-8 lg:grid-cols-2">{quantityGroups.map(([label, prefixes]) => <section key={label} className="mb-7 min-w-0"><h3 className="border-b border-line pb-3 font-display text-xl">{label}</h3><dl className="divide-y divide-line">{Object.entries(current.items).filter(([id]) => prefixes.some(p => id.startsWith(p))).map(([id, values]) => <div key={id} className="py-3"><dt className="text-sm capitalize">{id.replaceAll('.', ' · ').replace(/([a-z])([A-Z])/g, '$1 $2')}</dt><dd className="mt-2 flex flex-wrap items-baseline justify-between gap-2 text-xs text-ink-dim"><span>{Object.entries(values).filter(([, v]) => v > 0).map(([k, v]) => `${k} ${v.toFixed(2)}${k === 'NetVolume' ? ' m³' : k === 'Length' ? ' m' : k === 'Count' ? '' : ' m²'}`).join(' · ')}</span><Link to={`/workspace/plan?floor=${floor === 'all' ? q.perFloor[0]?.level ?? 0 : current.level}&highlight=${encodeURIComponent(id)}`} className="shrink-0 underline">Show on plan</Link></dd></div>)}</dl></section>)}</div>
    <section><h3 className="border-b border-line pb-3 font-display text-xl">Materials</h3><dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2"><div><dt>Steel</dt><dd className="text-ink-dim">{Object.values(current.steelKg).reduce((n, v) => n + v, 0).toFixed(1)} kg</dd></div><div><dt>Formwork</dt><dd className="text-ink-dim">{Object.values(current.formworkM2).reduce((n, v) => n + v, 0).toFixed(1)} m²</dd></div></dl>
      {floor === 'all' && <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt>{q.masonryMaterials.type}</dt><dd className="text-ink-dim">{Math.ceil(q.masonryMaterials.Count)} units</dd></div><div><dt>Water storage · whole home</dt><dd className="text-ink-dim">{q.tanks.overheadLitres} L overhead · {q.tanks.undergroundLitres} L underground</dd></div>{q.concreteMaterials.cementBags !== null ? <><div><dt>Cement · nominal M20 mix</dt><dd className="text-ink-dim">{q.concreteMaterials.cementBags.toFixed(1)} bags</dd></div><div><dt>Sand / aggregate · nominal M20 mix</dt><dd className="text-ink-dim">{q.concreteMaterials.sandM3?.toFixed(2)} / {q.concreteMaterials.aggregateM3?.toFixed(2)} m³</dd></div></> : <p className="text-xs text-ink-faint">Concrete constituent quantities require the specified design mix.</p>}</dl>}
      <p className="mt-5 text-xs leading-relaxed text-ink-faint">Member sizes and material ratios are approximate; structural design by a licensed engineer required. Aggregated rows and room breakdowns describe the same work and are not additional charges.</p></section>
  </section>
}
export function EstimateView({ cost, onAllowances }: { cost: CostEstimate; onAllowances: (change: Partial<CostSelection>) => void }) {
  const [split, setSplit] = useState(false)
  const download = () => { const url = URL.createObjectURL(new Blob(['\uFEFF', boqCsv(cost)], { type: 'text/csv;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = 'formstead-concept-boq.csv'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 4000) }
  return <section><div className="grid items-start gap-8 lg:grid-cols-[1fr_320px]"><div>
    <p className="label">Expected total</p><h2 className="mt-2 font-display text-4xl">{formatINR(cost.expected)}</h2><p className="mt-3 text-sm text-ink-dim">Range {formatRange(cost.total.low, cost.total.high, formatINR)}</p><p className="mt-2 text-sm">{formatINR(cost.ratePerSqft)} / sq ft</p><p className="mt-3 text-xs leading-relaxed text-ink-faint">{cost.qualification}</p>
    <div aria-label="Contract view" className="mt-6 flex gap-2">{['Turnkey', 'Material + labour'].map((v, i) => <button type="button" key={v} aria-pressed={split === !!i} onClick={() => setSplit(!!i)} className={cx('border px-3 py-2 text-xs', split === !!i ? 'border-ink bg-bg-inset' : 'border-line')}>{v}</button>)}</div>
    <p className="mt-3 text-xs text-ink-dim">{split ? `Materials ${formatINR(cost.procurement.material)} · Labour ${formatINR(cost.procurement.labour)} · Overhead ${formatINR(cost.procurement.overhead)}` : `Turnkey works ${formatINR(cost.procurement.turnkey)}, including overhead.`}</p><p className="mt-2 text-xs text-ink-faint">{cost.procurement.note} This view does not change the estimated project total.</p>
    <div className="mt-7 space-y-4">{cost.tradeTotals.map(t => <details key={t.trade} className="border-b border-line pb-4"><summary className="cursor-pointer text-sm"><span className="inline-flex w-[calc(100%-20px)] flex-wrap justify-between gap-2"><span>{t.trade}</span><span className="font-mono text-xs">{formatINR(t.amount)} · {(t.share * 100).toFixed(1)}%</span></span><span className="mt-3 block h-1.5 bg-bg-inset"><span className="block h-full bg-ink-dim" style={{ width: `${t.share * 100}%` }} /></span></summary>
      <ul className="mt-4 divide-y divide-line">{cost.boq.filter(l => l.group === t.trade).map(l => <li key={l.id} className="py-3 text-xs"><div className="flex justify-between gap-4"><p>{l.label}</p><p className="shrink-0">{formatINR(l.amount)}</p></div><p className="mt-1 text-ink-faint">{l.specification} · {l.qty.toFixed(2)} {l.unit} × {formatINR(l.rate)}</p>{split && <p className="mt-1 text-ink-faint">Material {formatINR(l.materialAmount)} · Labour {formatINR(l.labourAmount)}</p>}</li>)}</ul></details>)}</div><p className="mt-3 text-xs text-ink-faint">Trade shares are of works, before project add-ons.</p>
    <button type="button" onClick={download} className="mt-5 border border-line px-4 py-2 text-xs">Download BOQ CSV</button>
    </div><aside><h3 className="font-display text-xl">Project add-ons</h3><dl className="mt-3 divide-y divide-line">{cost.lines.slice(1).map(l => <div key={l.label} className="py-3 text-xs"><div className="flex justify-between gap-3"><dt>{l.label}</dt><dd className="shrink-0">{formatINR(l.expected)}</dd></div><p className="mt-1 text-ink-faint">{l.note}</p></div>)}</dl>
      <h3 className="mt-7 font-display text-xl">Top cost drivers</h3><p className="mt-2 text-xs text-ink-faint">Compared with the {{ simple: 'Basic', standard: 'Mid', refined: 'Premium' }[cost.selection.preset] ?? cost.selection.preset} defaults on this same plan.</p><ul className="mt-3 space-y-4">{cost.topCostDrivers.map(d => <li key={d.item} className="text-xs"><p>{d.label} · {formatINR(d.amount)}</p><p className="mt-1 text-ink-faint">{d.difference ? `${d.difference > 0 ? '+' : '−'}${formatINR(Math.abs(d.difference))} vs default` : 'Matches default'}</p></li>)}</ul></aside></div>
    <details className="mt-8 border-t border-line pt-4"><summary className="cursor-pointer text-sm">Allowances & tax provision</summary><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{([['overheadPercent', 'Overhead (%)'], ['contingencyPercent', 'Contingency (%)'], ['feePercent', 'Fees (%)'], ['gstPercent', 'GST (%)']] as const).map(([field, label]) => <Field key={field} label={label}><input aria-label={label} type="number" min={0} max={policy.percentageLimit} value={cost.selection[field]} onChange={e => { if (e.target.value !== '') onAllowances({ [field]: Number(e.target.value) }) }} className="w-full border border-line bg-bg p-2 text-sm" /></Field>)}</div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={cost.selection.includeGst} onChange={e => onAllowances({ includeGst: e.target.checked })} />Include GST provision</label></details>
  </section>
}
export function AssumptionsView({ cost }: { cost: CostEstimate }) {
  return <section><h2 className="font-display text-2xl">What this estimate covers</h2><p className="mt-3 max-w-3xl text-sm leading-relaxed text-ink-dim">{cost.qualification}</p><div className="mt-7 grid gap-8 md:grid-cols-2">{([['Included', cost.included], ['Excluded', cost.excluded], ['Assumptions', cost.assumptions], ['Rates source & date', cost.sources]] as const).map(([title, list]) => <section key={title} className="min-w-0 [overflow-wrap:anywhere]"><h3 className="border-b border-line pb-3 font-display text-xl">{title}</h3><ul className="mt-4 space-y-3 text-sm leading-relaxed text-ink-dim">{list.map(v => <li key={v}>{v}</li>)}</ul></section>)}</div><p className="mt-6 text-xs text-ink-faint">{cost.basis}</p>{cost.sanityNote && <p className="mt-3 text-xs text-ink-faint">{cost.sanityNote}</p>}</section>
}
